### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by corentindenoeud** [ControlCplusControlV/hardhat-Yul#2]
Hi, I have the following error when compiliing the SimpleStore contract, any clue ?

`  SimpleStore
    1) SimpleStore

  0 passing (601ms)
  1 failing

  1) SimpleStore
       SimpleStore:
     NomicLabsHardhatPluginError: You are trying to create a contract factory from an artifact, but you have not passed a valid artifact parameter.
      at getContractFactoryFromArtifact (/home/ubuntu/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:132:11)
      at getContractFactory (/home/ubuntu/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:101:12)
      at async Context.<anonymous> (/home/ubuntu/yul/test/test.js:6:25)`

**Comment by sewinter** [comment]
Did you end up solving this?

**Comment by ControlCplusControlV** [comment]
foundry supports compiling single Yul artifacts, would recommend using that instead at this point

**Comment by Isoltec** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
